- name: Restore dependencies
        run: |
          dotnet restore ${{ env.PROJECT_PATH }} \
            -r ${{ matrix.runtime }} \
            /p:PublishReadyToRun=true

      - name: Publish
        shell: pwsh
        run: |
          $publishArgs = @(
            "publish", "${{ env.PROJECT_PATH }}",
            "-c", "Release",
            "-r", "${{ matrix.runtime }}",
            "-o", "./publish/${{ matrix.runtime }}",
            "--self-contained", "true",
            "--no-restore", # We already restored with R2R=true above
            "/p:PublishSingleFile=true",
            "/p:PublishReadyToRun=true",
            "/p:PublishTrimmed=true",
            "/p:TrimMode=full",
            "/p:DebugType=None",
            "/p:DebugSymbols=false"
          )

          # Special flag for macOS to ensure the AppHost is generated
          if ("${{ matrix.runtime }}".StartsWith("osx-")) {
            $publishArgs += "/p:UseAppHost=true"
          }

          # Execute
          dotnet @publishArgs
